### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ItzDaSrijan** [Adivise/NanoSpace#17]
the loadEvent.js says evt.bind isnt a function and the code wont work, i thought it might be cuz of using 2 repos for same bot but i tried with a brand new bot it didnt work either, i reforked did everything no work

**Comment by Adivise** [comment]
> the loadEvent.js says evt.bind isnt a function and the code wont work, i thought it might be cuz of using 2 repos for same bot but i tried with a brand new bot it didnt work either, i reforked did everything no work

what command have error, when use?

on me start bot not say anything error!

**Comment by Shabbir260505** [comment]
As I said earlier, it is issue on your side, when u reforked, how did it work? And later on stopped working. Please be sure u refork and don't edit code by any means. Even if u add just a bracket, the code will stop working

**Comment by ItzDaSrijan** [comment]
i didnt do anything
