### ISSUE TITLE
song has error, auto leaving

### ISSUE THREAD

**Issue by nlrvr** [Adivise/NanoSpace#18]
not matching the ones specified

**Comment by Adivise** [comment]
> not matching the ones specified

`this reason have 3 problem`

1. Age Verification!
2. Source of song use to play!
3. Video got deleted from source!

#ask me, what you using source to play? (youtube? or etc.)

**Comment by nlrvr** [comment]
youtube

**Comment by Adivise** [comment]
> youtube

show me the picture of console bot having error all or screen shot on playing!

**Comment by nlrvr** [comment]
![1](https://user-images.githubusercontent.com/82196892/156910750-311f2825-7658-4678-bdee-e4dd63112bfc.jpg)

**Comment by Adivise** [comment]
what a song?

**Comment by nlrvr** [comment]
random songs
check this too, it plays different from the one specified
![image](https://user-images.githubusercontent.com/82196892/156910823-cd7f2f0e-a4df-4954-897d-49b656c33348.png)

**Comment by Adivise** [comment]
hmm idk, last check in lavalink console log, what is this error!
