### ISSUE TITLE
Songs not playing

### ISSUE THREAD

**Issue by theseeker99** [Adivise/NanoSpace#29]
SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at Y.json (/root/NanoSpace/node_modules/petitio/dist/index.js:30:574)
    at ke.json (/root/NanoSpace/node_modules/petitio/dist/index.js:30:2499)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by XeonE52680v3** [comment]
@theseeker99 you can use `npm start` or `yarn start` to use `node v17`. Because this issue is from elerajs not integrated with `node v18`. MenuDocs will fix soon.

**Comment by AADI0009** [comment]
instead of node 17 or 18 use LTS and erela.js has stopped using petitio in their build
better use `npm install menudocs/erela.js#build`

**Comment by theseeker99** [comment]
Tnx man, it's really helped me.

**Comment by theseeker99** [comment]
> @theseeker99 you can use `npm start` or `yarn start` to use `node v17`. Because this issue is from elerajs not integrated with `node v18`. MenuDocs will fix soon.

Tnx man, it's really helped me.

**Comment by theseeker99** [comment]
> instead of node 17 or 18 use LTS and erela.js has stopped using petitio in their build better use `npm install menudocs/erela.js#build`

Tnx man

**Comment by XeonE52680v3** [comment]
@theseeker99 can you close the issue
