### ISSUE TITLE
......

### ISSUE THREAD

**Issue by sam920829** [Adivise/NanoSpace#3]
Error: Cannot find module 'node:events'
Require stack:
- C:\Users\user\Downloads\NanoSpace-master\NanoSpace-master\node_modules\discord.js\src\client\BaseClient.js
- C:\Users\user\Downloads\NanoSpace-master\NanoSpace-master\node_modules\discord.js\src\index.js
- C:\Users\user\Downloads\NanoSpace-master\NanoSpace-master\nanospace.js
- C:\Users\user\Downloads\NanoSpace-master\NanoSpace-master\index.js
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:725:27)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:952:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:88:18)[39m
    at Object.<anonymous> (C:\Users\user\Downloads\NanoSpace-master\NanoSpace-master\node_modules\[4mdiscord.js[24m\src\client\BaseClient.js:3:22)
[90m    at Module._compile (internal/modules/cjs/loader.js:1063:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:928:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:952:19)[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: [
    [32m'C:\\Users\\user\\Downloads\\NanoSpace-master\\NanoSpace-master\\node_modules\\discord.js\\src\\client\\BaseClient.js'[39m,
    [32m'C:\\Users\\user\\Downloads\\NanoSpace-master\\NanoSpace-master\\node_modules\\discord.js\\src\\index.js'[39m,
    [32m'C:\\Users\\user\\Downloads\\NanoSpace-master\\NanoSpace-master\\nanospace.js'[39m,
    [32m'C:\\Users\\user\\Downloads\\NanoSpace-master\\NanoSpace-master\\index.js'[39m
  ]
}

**Comment by Adivise** [comment]
please install node v16+ or higher https://nodejs.org/en/
